name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build

      - name: Export static HTML with Next.js
        run: npm run export

      - name: Upload Static Site
        uses: actions/upload-artifact@v2
        with:
          name: static-site
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Static Site
        uses: actions/download-artifact@v2
        with:
          name: static-site
          path: out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./out
